# Generated by Django 3.1.6 on 2021-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='requires_approval',
        ),
        migrations.AddField(
            model_name='loantype',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
