# Generated by Django 3.1.6 on 2021-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_auto_20210309_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user_fk',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
    ]
