# Generated by Django 3.1.6 on 2021-03-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_loan_loan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='approved',
        ),
    ]
