# Generated by Django 3.1.6 on 2021-03-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_rank_can_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
